Bundler/OrderedGems:
  Exclude:
    - 'gemfiles/*.gemfile'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'bin/**/*'
    - 'gemfiles/*.gemfile'
    - 'spec/dummy/bin/**/*'

Style/StringLiterals:
  Exclude:
    - 'gemfiles/*.gemfile'
