version: 2.1
orbs:
  ruby: circleci/ruby@1.1
commands:
  configure_bundler:
    description: Configure bundler
    steps:
      - run:
          name: Configure bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
jobs:
  build:
    environment:
      RAILS_ENV: test
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - configure_bundler
      - run:
          name: Install Ruby Dependencies
          command: bundle install --jobs=4 --retry=3
      - run:
          name: Run Rspec tests
          command: bundle exec rspec spec
workflows:
  version: 2
  integration:
    jobs:
      - build:
          pre-steps:
            - run:
                name: Install Code Climate Reporter
                command: |
                  curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > /tmp/cc-test-reporter
                  chmod +x /tmp/cc-test-reporter
            - run:
                name: Setup Code Climate Reporter
                command: /tmp/cc-test-reporter before-build
          post-steps:
            - run:
                name: Upload Code Climate report
                command: /tmp/cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?
